In [2]:
import torch
from numpy import ndarray

tensor1 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(
    tensor1
    ,
    tensor1.dtype
    ,
    tensor1.device
    ,
    tensor1.requires_grad
)

tensor([1, 2, 3], dtype=torch.int32) torch.int32 cpu False


In [3]:
tensor2 = torch.empty((3, 2, 4), dtype=torch.float64)
print(tensor2)

tensor([[[3.1653e-311,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],
       dtype=torch.float64)


In [4]:
tensor3 = torch.randn_like(tensor2)
print(tensor3)

tensor([[[-0.3654, -2.4723, -0.7709, -0.7319],
         [-0.5012,  0.6845, -1.7030,  0.2509]],

        [[ 0.3307,  0.8291,  0.9042, -0.6475],
         [ 0.5983,  2.6154,  1.0908,  0.3148]],

        [[-0.9323,  0.1082,  0.8519, -1.0310],
         [-1.2877,  1.0390,  1.0943,  0.3721]]], dtype=torch.float64)


In [5]:
ndarray1 = tensor3.clone().numpy()
ndarray2 = tensor3.numpy().copy()
print(ndarray1)
print(ndarray2)

[[[-0.36538499 -2.47225463 -0.77089579 -0.73191138]
  [-0.501154    0.68446224 -1.70299332  0.25092497]]

 [[ 0.33065875  0.82907159  0.90423883 -0.64747892]
  [ 0.59831355  2.61540917  1.09081894  0.31483568]]

 [[-0.93228128  0.1082299   0.85188936 -1.03097735]
  [-1.28765651  1.03901177  1.0942787   0.37210372]]]
[[[-0.36538499 -2.47225463 -0.77089579 -0.73191138]
  [-0.501154    0.68446224 -1.70299332  0.25092497]]

 [[ 0.33065875  0.82907159  0.90423883 -0.64747892]
  [ 0.59831355  2.61540917  1.09081894  0.31483568]]

 [[-0.93228128  0.1082299   0.85188936 -1.03097735]
  [-1.28765651  1.03901177  1.0942787   0.37210372]]]


In [7]:
tensor_1 = torch.randn(2,3,5)
tensor_2 = torch.randn(2,2,5)
# print(tensor_1 @ tensor_2)
# 最后一个张量维度等于第二个张量倒是第二个维度，前面的维度满足广播机制可矩阵乘法