In [1]:
import torch
from numpy.lib.tests.test_format import dtype

## 1. 基于内容创建tensor

In [4]:
# 1. 标量
t1 = torch.tensor(10)
print(t1)
print(t1.shape)

tensor(10)
torch.Size([])


In [5]:
# 2. 列表
t1 = torch.tensor([10, 20, 30])
print(t1)
print(t1.shape)

tensor([10, 20, 30])
torch.Size([3])


In [6]:
# 3. 矩阵
t1 = torch.tensor([[10, 20, 30], [100, 200, 300]])
print(t1)
print(t1.shape)

tensor([[ 10,  20,  30],
        [100, 200, 300]])
torch.Size([2, 3])


In [7]:
# 4. 矩阵
t1 = torch.tensor([ [[10, 20, 30], [100, 200, 300]] , [[10, 20, 30], [100, 200, 300]]])
print(t1)
print(t1.shape)

tensor([[[ 10,  20,  30],
         [100, 200, 300]],

        [[ 10,  20,  30],
         [100, 200, 300]]])
torch.Size([2, 2, 3])


In [8]:
# 5. numpy的ndarray
import numpy as np
t1 = torch.tensor(np.array([[10, 20, 30], [100, 200, 300]]))
print(t1)
print(t1.shape)


tensor([[ 10,  20,  30],
        [100, 200, 300]])
torch.Size([2, 3])


In [11]:
## 数据类型: 默认是根据传入数据的类型
t1 = torch.tensor([[10, 20, 30], [100, 200, 300]])
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[ 10,  20,  30],
        [100, 200, 300]])
torch.Size([2, 3])
torch.int64


## 2. 基于形状创建tensor

In [12]:
t1 = torch.Tensor(2,3)  # 类型默认float32
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.float32


## 总结
1. 基于内存创建用小写tensor, 类型由传入的数据类定
2. 基于形状创建用的大写的tensor, 类型是默认float32

## 3. 创建指定类型的tensor

In [14]:
t1 = torch.tensor([1,3], dtype=torch.float)
print(t1)
print(t1.shape)
print(t1.dtype)


tensor([1., 3.])
torch.Size([2])
torch.float32


In [15]:
t1 = torch.tensor([1,3]).float()
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([1., 3.])
torch.Size([2])
torch.float32


In [16]:
t1 = torch.tensor([1,3]).to(torch.float)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([1., 3.])
torch.Size([2])
torch.float32


In [24]:
t1 = torch.LongTensor(2,3)  # int64
t1 = torch.IntTensor(2,3) # int32
t1 = torch.ShortTensor(2,3) # int16
t1 = torch.ByteTensor(2,3) # uint8
t1 = torch.FloatTensor(2,3) # float32
t1 = torch.DoubleTensor(2,3) # float64
t1 = torch.HalfTensor(2,3) # float16
t1 = torch.BoolTensor(2,3) # Bool
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[False, False, False],
        [False, False, False]])
torch.Size([2, 3])
torch.bool


## 4. 基于区间创建

In [26]:
t1 = torch.arange(start=1, end=10, step=2)  # [1, 10)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([1, 3, 5, 7, 9])
torch.Size([5])
torch.int64


In [27]:
t1 = torch.arange(10)  # [0, 10)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
torch.int64


In [29]:
t1 = torch.linspace(1, 9, 10)  # [start, end] step = (end-start)/(steps - 1)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([1.0000, 1.8889, 2.7778, 3.6667, 4.5556, 5.4444, 6.3333, 7.2222, 8.1111,
        9.0000])
torch.Size([10])
torch.float32


In [32]:
t1 = torch.logspace(1, 3, 5, base=torch.e)  #  10^1  10^2 10^3
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([ 2.7183,  4.4817,  7.3891, 12.1825, 20.0855])
torch.Size([5])
torch.float32


## 5. 基于填充创建

In [35]:
t1 = torch.ones(3, 4)
print(t1)
print(t1.shape)

t2 = torch.ones_like(t1)
print(t2)
print(t2.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])


In [36]:
t1 = torch.zeros(3, 4)
print(t1)
print(t1.shape)

t2 = torch.zeros_like(t1)
print(t2)
print(t2.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])


In [38]:
t2 = torch.empty(2,3)
print(t2)
print(t2.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [39]:
t2 = torch.full((2,3), 10)
print(t2)
print(t2.shape)

tensor([[10, 10, 10],
        [10, 10, 10]])
torch.Size([2, 3])


In [40]:
t2 = torch.eye(5)
print(t2)
print(t2.shape)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
torch.Size([5, 5])


## 6. 随机创建

In [43]:
## 均匀分布: [0, 1)
t1 = torch.rand(2,3)
print(t1)
print(t1.shape)

tensor([[0.8631, 0.9311, 0.0916],
        [0.4091, 0.3211, 0.7786]])
torch.Size([2, 3])


In [52]:
## 均匀分布整数
t1 = torch.randint(1, 10, (2,3))
print(t1)
print(t1.shape)


tensor([[8, 4, 5],
        [3, 8, 4]])
torch.Size([2, 3])


In [53]:
## 正态分布: 标准正态分布: 均值0 标准差1
t1 = torch.randn(2,3)
print(t1)
print(t1.shape)


tensor([[ 0.4162, -0.7551, -1.2299],
        [ 0.8854,  1.2230, -0.3622]])
torch.Size([2, 3])


In [65]:
## 正态分布: 标准正态分布: 均值0 标准差1
t1 = torch.normal(mean=0, std=1, size=(2,3))
print(t1)
print(t1.shape)

tensor([[ 0.3656,  0.5628,  1.0276],
        [-0.7742, -0.2614,  1.0041]])
torch.Size([2, 3])


In [92]:
# 洗牌
t1 = torch.randperm(100)
print(t1)
print(t1.shape)

tensor([13,  8, 64, 29, 70,  5, 58, 78, 97, 57, 33, 62,  6,  1, 74, 76, 65, 63,
        59, 34, 46, 44, 56, 36, 15, 38, 20, 17, 39, 37, 40, 32, 24,  7, 67, 89,
        19, 52, 93, 31, 82, 73, 95, 71, 30, 69, 61, 92, 85, 23, 22, 81, 87, 12,
        16, 45, 91, 35, 25, 88, 60, 79, 75, 53, 48,  0, 72, 99, 94, 27, 86, 80,
        49, 10, 51, 18, 26, 41, 77, 21, 54, 55, 28, 11, 98, 14,  4,  9, 84, 43,
        50,  2, 42, 90, 68, 83, 47, 96, 66,  3])
torch.Size([100])


In [101]:
# 查看随机数种子
print(torch.initial_seed())

42


In [100]:
torch.manual_seed(42)