In [1]:
import torch

## 类型的转换

In [2]:
t1 = torch.tensor([10, 20])

In [4]:
t2 = t1.type(torch.float32)
print(t2)
print(t2.dtype)

tensor([10., 20.])
torch.float32


In [5]:
t2 = t1.to(torch.float32)
print(t2.dtype)

torch.float32


In [7]:
t2 = t1.float()
print(t2.dtype)

torch.int64


## tensor=>ndarray的转换

In [8]:
## tensor => ndarray
t1 = torch.tensor([10, 20])
n1 = t1.numpy() # 内存共享
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[10 20]


In [10]:
t1[0] = 100
print(t1)
print(n1)

tensor([100,  20])
[100  20]


In [12]:
#避免内存共享
n2 = t1.numpy().copy()
print(n2)
t1[0] = 200
print(n2)

[100  20]
[100  20]


## ndarray=>tensor

In [13]:
import numpy as np

n1 = np.array([10, 20])

In [15]:
t1 = torch.from_numpy(n1)  # 内存共享
print(t1)
n1[0] = 100
print(t1)

tensor([10, 20])
tensor([100,  20])


In [17]:
t1 = torch.from_numpy(n1).clone()
print(t1)
n1[0] = 200
print(t1)

tensor([100,  20])
tensor([100,  20])


## tensor=>标量

In [18]:
t1 = torch.tensor([10, 20])


In [20]:
print(t1[0].item())  # tensor的内容只有一个元素

10


In [28]:
t1 = torch.tensor([[[10]]])
print(t1.shape)
print(type(t1.shape))
print(t1.item())

1
<class 'torch.Size'>
10
