In [1]:
import torch

## 1. 基本运算 + - * /

In [4]:
t1 = torch.tensor([10, 20, 30])
print(t1 + 10)

print(t1.add(10))

print(t1)
t1.add_(10)  # 修改t1的内容
print(t1)

tensor([20, 30, 40])
tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([20, 30, 40])


## 元素级运算 (tensor和tensor)

In [10]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[10, 20, 30], [40, 50, 60]])


In [9]:
# tensor+tensor
t2 = torch.tensor([[10], [60]])  # (2,3) (2, 1) 可以广播
print(t1 + t2)

tensor([[11, 12, 13],
        [64, 65, 66]])


In [13]:
# tensor+tensor  对位相乘  哈达玛积
print(t1 * t2)
print(t1.mul(t2))
print(t1.mul_(t2))
print(t1)

tensor([[ 10,  40,  90],
        [160, 250, 360]])
tensor([[ 10,  40,  90],
        [160, 250, 360]])
tensor([[ 10,  40,  90],
        [160, 250, 360]])
tensor([[ 10,  40,  90],
        [160, 250, 360]])


## 矩阵相乘


In [17]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [20]:
print(t1 @ t2)
print(t1.mm(t2))
print(t1.matmul(t2))

tensor([[300, 360, 420],
        [660, 810, 960]])
tensor([[300, 360, 420],
        [660, 810, 960]])
tensor([[300, 360, 420],
        [660, 810, 960]])


In [29]:
t1 = torch.tensor([[[1, 2, 3], [4, 5, 6], [6, 5, 4]], [[3, 2, 1], [3, 2, 1], [3, 2, 1]]])
t2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])


In [33]:
print(t1.shape, t2.shape)
print(t1 @ t2)  # 高维度相乘: 最后两个维度满足矩阵相乘, 其他维度保持一致或者满足广播原则
print(t1.matmul(t2))
print(t1.mm(t2))  # mm只能用于矩阵

torch.Size([2, 3, 3]) torch.Size([2, 3, 2])
tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])


RuntimeError: self must be a matrix

## 统计运算

In [39]:
t1 = torch.randint(1, 10, (2, 3, 5))
print(t1)
print(t1.shape)

tensor([[[5, 7, 2, 4, 1],
         [5, 9, 3, 9, 9],
         [3, 4, 6, 8, 7]],

        [[6, 8, 8, 2, 2],
         [1, 5, 2, 1, 1],
         [4, 1, 1, 4, 2]]])
torch.Size([2, 3, 5])


In [40]:
print(t1.sum())

tensor(130)


In [41]:
print(t1.sum(dim=0))

tensor([[11, 15, 10,  6,  3],
        [ 6, 14,  5, 10, 10],
        [ 7,  5,  7, 12,  9]])


In [42]:
print(t1.sum(dim=1))

tensor([[13, 20, 11, 21, 17],
        [11, 14, 11,  7,  5]])


In [43]:
print(t1.sum(dim=2))

tensor([[19, 35, 28],
        [26, 10, 12]])


In [46]:
print(t1.max())
print(t1.argmax())  # 最大值的下标

tensor(9)
tensor(6)


In [48]:
print(t1.max(dim=1))

torch.return_types.max(
values=tensor([[5, 9, 6, 9, 9],
        [6, 8, 8, 4, 2]]),
indices=tensor([[0, 1, 2, 1, 1],
        [0, 0, 0, 2, 0]]))


In [50]:
## 均值
print(t1.float().mean())

tensor(4.3333)


In [51]:
print(t1.float().mean(dim=0))

tensor([[5.5000, 7.5000, 5.0000, 3.0000, 1.5000],
        [3.0000, 7.0000, 2.5000, 5.0000, 5.0000],
        [3.5000, 2.5000, 3.5000, 6.0000, 4.5000]])


In [53]:
# var和std
print(t1.float().std())
print(t1.float().var())

tensor(2.7834)
tensor(7.7471)


In [65]:
print(t1.float().std(dim = 1))
print(t1.float().var(dim = 1))

tensor([[1.1547, 2.5166, 2.0817, 2.6458, 4.1633],
        [2.5166, 3.5119, 3.7859, 1.5275, 0.5774]])
tensor([[ 1.3333,  6.3333,  4.3333,  7.0000, 17.3333],
        [ 6.3333, 12.3333, 14.3333,  2.3333,  0.3333]])


In [68]:
t1[1,0,0] = 5
print(t1.float().unique())

tensor([[[5., 7., 2., 4., 1.],
         [5., 9., 3., 9., 9.],
         [3., 4., 6., 8., 7.]],

        [[5., 8., 8., 2., 2.],
         [1., 5., 2., 1., 1.],
         [4., 1., 1., 4., 2.]]])


In [70]:
print(t1.float().sort(dim=0)) # 默认=>dim=2

torch.return_types.sort(
values=tensor([[[5., 7., 2., 2., 1.],
         [1., 5., 2., 1., 1.],
         [3., 1., 1., 4., 2.]],

        [[5., 8., 8., 4., 2.],
         [5., 9., 3., 9., 9.],
         [4., 4., 6., 8., 7.]]]),
indices=tensor([[[0, 0, 0, 1, 0],
         [1, 1, 1, 1, 1],
         [0, 1, 1, 1, 1]],

        [[1, 1, 1, 0, 1],
         [0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0]]]))
