In [2]:
import torch
t = torch.randint(0, 10, (2, 5, 4))
print(t)
print(t.shape)

tensor([[[8, 3, 6, 4],
         [1, 3, 2, 0],
         [7, 2, 7, 1],
         [7, 1, 2, 8],
         [6, 7, 6, 8]],

        [[0, 8, 3, 4],
         [3, 6, 4, 5],
         [9, 0, 8, 0],
         [3, 7, 5, 1],
         [3, 9, 3, 3]]])
torch.Size([2, 5, 4])


## 简单索引

In [6]:
print(t[0][0][0])
print(t[1][1])

print(t[0,0,0])
print(t[1,1])

tensor(8)
tensor([3, 6, 4, 5])
tensor(8)
tensor([3, 6, 4, 5])


## 范围索引

In [7]:
print(t[1, 1:])

tensor([[3, 6, 4, 5],
        [9, 0, 8, 0],
        [3, 7, 5, 1],
        [3, 9, 3, 3]])


In [11]:
print(t[1, 1:-2:2])

tensor([[3, 6, 4, 5]])


## 列表索引

In [12]:
list1=[0,1]
list2=[1,2]
list3=[2,2]
print(t[list1,list2, list3])

tensor([2, 8])


In [13]:
list1=[0,1]
list2=[1,2]
print(t[list1,list2])

tensor([[1, 3, 2, 0],
        [9, 0, 8, 0]])


In [14]:
list1=[[0],[1]]
list2=[1,2]
print(t[list1,list2])

tensor([[[1, 3, 2, 0],
         [7, 2, 7, 1]],

        [[3, 6, 4, 5],
         [9, 0, 8, 0]]])


In [16]:
list1 = [0,1,3,4,5,2]
# 变成独热编码
t1 = torch.zeros(6, 6)
t1[[0,1,2,3,4,5], list1] = 1
print(t1)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0.]])


## 布尔索引

In [19]:
# 取出所有的大于5的值
mask = t > 5
print(mask)

tensor([[[ True, False,  True, False],
         [False, False, False, False],
         [ True, False,  True, False],
         [ True, False, False,  True],
         [ True,  True,  True,  True]],

        [[False,  True, False, False],
         [False,  True, False, False],
         [ True, False,  True, False],
         [False,  True, False, False],
         [False,  True, False, False]]])


In [20]:
print(t[mask])

tensor([8, 6, 7, 7, 7, 8, 6, 7, 6, 8, 8, 6, 9, 8, 7, 9])


In [23]:
# 取出所有行中,首元素于5的那些行
mask = t[:, :, 0] > 5
print(mask)

tensor([[ True, False,  True,  True,  True],
        [False, False,  True, False, False]])


In [24]:
print(t[mask])

tensor([[8, 3, 6, 4],
        [7, 2, 7, 1],
        [7, 1, 2, 8],
        [6, 7, 6, 8],
        [9, 0, 8, 0]])


In [25]:
# 取出所有列中,首元素于5的那些列
mask = t[:, 0, :] > 5
print(mask)

tensor([[ True, False,  True, False],
        [False,  True, False, False]])


In [28]:
print(t.mT[mask].mT)

tensor([[8, 6, 8],
        [1, 2, 6],
        [7, 7, 0],
        [7, 2, 7],
        [6, 6, 9]])
