In [8]:
import torch
t1 = torch.randint(1, 10, (3,2,6))
print(t1)
print(t1.shape)


tensor([[[5, 7, 3, 5, 4, 7],
         [1, 4, 8, 7, 9, 6]],

        [[6, 3, 7, 1, 8, 6],
         [5, 6, 7, 4, 8, 9]],

        [[9, 9, 8, 1, 7, 1],
         [1, 6, 2, 5, 8, 5]]])
torch.Size([3, 2, 6])


## 维度变换

In [9]:
## 转置的本质: 索引的交换   (1,1,4) => (4,1,1)
print(t1.T)
print(t1.T.shape)

tensor([[[5, 6, 9],
         [1, 5, 1]],

        [[7, 3, 9],
         [4, 6, 6]],

        [[3, 7, 8],
         [8, 7, 2]],

        [[5, 1, 1],
         [7, 4, 5]],

        [[4, 8, 7],
         [9, 8, 8]],

        [[7, 6, 1],
         [6, 9, 5]]])
torch.Size([6, 2, 3])


In [10]:
print(t1.mT)

tensor([[[5, 1],
         [7, 4],
         [3, 8],
         [5, 7],
         [4, 9],
         [7, 6]],

        [[6, 5],
         [3, 6],
         [7, 7],
         [1, 4],
         [8, 8],
         [6, 9]],

        [[9, 1],
         [9, 6],
         [8, 2],
         [1, 5],
         [7, 8],
         [1, 5]]])


In [11]:
## 交换任意两个维度
print(t1.transpose(0, 1))  # (1,0,0) => (0,1,0)

tensor([[[5, 7, 3, 5, 4, 7],
         [6, 3, 7, 1, 8, 6],
         [9, 9, 8, 1, 7, 1]],

        [[1, 4, 8, 7, 9, 6],
         [5, 6, 7, 4, 8, 9],
         [1, 6, 2, 5, 8, 5]]])


In [14]:
# 重排所有维度
t2 = t1.permute(2,1,0)
print(t2)
print(t2.shape)

tensor([[[5, 6, 9],
         [1, 5, 1]],

        [[7, 3, 9],
         [4, 6, 6]],

        [[3, 7, 8],
         [8, 7, 2]],

        [[5, 1, 1],
         [7, 4, 5]],

        [[4, 8, 7],
         [9, 8, 8]],

        [[7, 6, 1],
         [6, 9, 5]]])
torch.Size([6, 2, 3])


## shape的调制

In [18]:
# 1. reshape
print(t1.reshape(-1))

tensor([5, 7, 3, 5, 4, 7, 1, 4, 8, 7, 9, 6, 6, 3, 7, 1, 8, 6, 5, 6, 7, 4, 8, 9,
        9, 9, 8, 1, 7, 1, 1, 6, 2, 5, 8, 5])


In [24]:
print(t1.reshape(-1,9))


tensor([[5, 7, 3, 5, 4, 7, 1, 4, 8],
        [7, 9, 6, 6, 3, 7, 1, 8, 6],
        [5, 6, 7, 4, 8, 9, 9, 9, 8],
        [1, 7, 1, 1, 6, 2, 5, 8, 5]])


In [29]:
print(t1.reshape(3,1, 2,-1))

tensor([[[[5, 7, 3, 5, 4, 7],
          [1, 4, 8, 7, 9, 6]]],


        [[[6, 3, 7, 1, 8, 6],
          [5, 6, 7, 4, 8, 9]]],


        [[[9, 9, 8, 1, 7, 1],
          [1, 6, 2, 5, 8, 5]]]])


In [30]:
# view
print(t1.view(3, 1, 2, -1))

tensor([[[[5, 7, 3, 5, 4, 7],
          [1, 4, 8, 7, 9, 6]]],


        [[[6, 3, 7, 1, 8, 6],
          [5, 6, 7, 4, 8, 9]]],


        [[[9, 9, 8, 1, 7, 1],
          [1, 6, 2, 5, 8, 5]]]])


In [31]:
print(t1.mT.reshape(-1))

tensor([5, 1, 7, 4, 3, 8, 5, 7, 4, 9, 7, 6, 6, 5, 3, 6, 7, 7, 1, 4, 8, 8, 6, 9,
        9, 1, 9, 6, 8, 2, 1, 5, 7, 8, 1, 5])


In [34]:
#print(t1.mT.view(-1))
print(t1.is_contiguous())
print(t1.mT.is_contiguous())

# 强制内存连续
print(t1.mT.contiguous().view(-1))


True
False
tensor([5, 1, 7, 4, 3, 8, 5, 7, 4, 9, 7, 6, 6, 5, 3, 6, 7, 7, 1, 4, 8, 8, 6, 9,
        9, 1, 9, 6, 8, 2, 1, 5, 7, 8, 1, 5])


## 增删维度(增加维度1或者删除所有的1的维度)

In [42]:
t2 = t1.unsqueeze(dim=-1)
print(t2.shape)
print(t2)

torch.Size([3, 2, 6, 1])
tensor([[[[5],
          [7],
          [3],
          [5],
          [4],
          [7]],

         [[1],
          [4],
          [8],
          [7],
          [9],
          [6]]],


        [[[6],
          [3],
          [7],
          [1],
          [8],
          [6]],

         [[5],
          [6],
          [7],
          [4],
          [8],
          [9]]],


        [[[9],
          [9],
          [8],
          [1],
          [7],
          [1]],

         [[1],
          [6],
          [2],
          [5],
          [8],
          [5]]]])


In [44]:
t2 = t1.reshape(1,1,1,-1)
print(t2.shape)
t3 = t2.squeeze()
print(t3.shape)
print(t3)

torch.Size([1, 1, 1, 36])
torch.Size([36])
tensor([5, 7, 3, 5, 4, 7, 1, 4, 8, 7, 9, 6, 6, 3, 7, 1, 8, 6, 5, 6, 7, 4, 8, 9,
        9, 9, 8, 1, 7, 1, 1, 6, 2, 5, 8, 5])


## tensor的拼接

In [48]:
t1 = torch.randint(1, 10, (2, 1, 3))
t2 = torch.randint(1, 10, (2, 3, 3))
print(t1)
print(t2)

tensor([[[7, 7, 5]],

        [[1, 5, 9]]])
tensor([[[7, 1, 2],
         [8, 7, 6],
         [4, 2, 8]],

        [[6, 3, 3],
         [2, 8, 9],
         [7, 5, 2]]])


In [51]:
t3 = torch.cat((t1, t2), dim=1)  # 处理dim=1 , 其他必须匹配
print(t3)

tensor([[[7, 7, 5],
         [7, 1, 2],
         [8, 7, 6],
         [4, 2, 8]],

        [[1, 5, 9],
         [6, 3, 3],
         [2, 8, 9],
         [7, 5, 2]]])


In [58]:
# stack: 先做 unsqueeze, 然后再 cat
t1 = torch.randint(1, 10, (2, 3, 3))
t2 = torch.randint(1, 10, (2, 3, 3))

t3 = torch.stack((t1, t2), dim=0)
print(t3)
print(t3.shape)



tensor([[[[5, 4, 6],
          [3, 5, 7],
          [5, 8, 6]],

         [[6, 9, 1],
          [8, 1, 6],
          [3, 1, 8]]],


        [[[1, 4, 6],
          [3, 6, 3],
          [4, 6, 2]],

         [[9, 3, 1],
          [3, 9, 4],
          [6, 5, 1]]]])
torch.Size([2, 2, 3, 3])


In [66]:
t1 = torch.randint(1, 10, (2, 3))
t2 = torch.randint(1, 10, (2, 3))
t3 = torch.vstack((t1,t2))
print(t1)
print(t2)
print(t3)

tensor([[5, 2, 8],
        [8, 1, 5]])
tensor([[8, 4, 1],
        [7, 1, 1]])
tensor([[5, 2, 8],
        [8, 1, 5],
        [8, 4, 1],
        [7, 1, 1]])
