In [5]:
import torch
import torch.nn as nn

In [6]:
# 定义一个全连接处
linear = nn.Linear(2, 3)

## 常数初始化

In [7]:
print(linear.weight)
print(linear.bias)
nn.init.zeros_(linear.weight)
nn.init.zeros_(linear.bias)
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.3847,  0.3911],
        [-0.2364, -0.5667],
        [-0.2854, -0.6873]], requires_grad=True)
Parameter containing:
tensor([-0.4533, -0.2028, -0.0014], requires_grad=True)
Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [8]:
nn.init.ones_(linear.weight)
nn.init.ones_(linear.bias)
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
Parameter containing:
tensor([1., 1., 1.], requires_grad=True)


In [9]:
nn.init.constant_(linear.weight, 10)
nn.init.constant_(linear.bias, 10)
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[10., 10.],
        [10., 10.],
        [10., 10.]], requires_grad=True)
Parameter containing:
tensor([10., 10., 10.], requires_grad=True)


In [10]:
## 特殊常数初始化(秩初始化)
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]], requires_grad=True)


## 随机初始化

In [15]:
# 把参数初始化位正态分布: 默认是标准正态分布
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[-0.4528, -0.0784],
        [-1.4841, -0.1293],
        [ 1.2924, -0.3366]], requires_grad=True)


In [25]:
# 把参数初始化均匀分布
nn.init.uniform_(linear.weight, a=1, b=2)
print(linear.weight)

Parameter containing:
tensor([[1.1086, 1.3967],
        [1.8442, 1.4778],
        [1.4100, 1.8499]], requires_grad=True)


## xavier 初始化

In [26]:
nn.init.xavier_normal_(linear.weight)

Parameter containing:
tensor([[-0.4945, -0.9949],
        [ 1.2556, -0.5731],
        [-0.3814, -0.5465]], requires_grad=True)

In [27]:
nn.init.xavier_uniform_(linear.weight)

Parameter containing:
tensor([[ 0.7892,  0.5470],
        [ 0.9888,  1.0889],
        [ 0.7653, -0.4195]], requires_grad=True)

## He初始化(凯明初始化)

In [30]:
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 7.4345e-01, -5.9417e-04],
        [ 4.7758e-02,  2.9965e-01],
        [-1.4370e+00, -1.8580e+00]], requires_grad=True)


In [31]:
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 1.1122, -0.3834],
        [ 1.1639, -1.3174],
        [-0.4978, -0.8495]], requires_grad=True)
