In [1]:
import torch
import torch.nn as nn
from torch.optim import SGD

## BN层

In [2]:
x = torch.randint(0, 10, (5, 3)).float()
print(x)


tensor([[5., 1., 8.],
        [3., 4., 2.],
        [9., 4., 6.],
        [2., 5., 0.],
        [7., 5., 4.]])


In [3]:
bn = nn.BatchNorm1d(num_features=3)

In [4]:
y = bn(x)
print(y)

tensor([[-0.0781, -1.9052,  1.4142],
        [-0.8590,  0.1361, -0.7071],
        [ 1.4836,  0.1361,  0.7071],
        [-1.2494,  0.8165, -1.4142],
        [ 0.7028,  0.8165,  0.0000]], grad_fn=<NativeBatchNormBackward0>)


## 权值衰减

In [ ]:
SGD(weight_decay=0.2)

## Dropout

In [5]:
x = torch.randint(1, 10, (10, )).float()
print(x)


tensor([8., 1., 5., 9., 8., 2., 3., 2., 9., 7.])


In [9]:
dp = nn.Dropout(p = 0.5)
y = dp(x)
print(y)

tensor([16.,  2., 10., 18.,  0.,  4.,  0.,  4.,  0.,  0.])
