In [1]:
import torch
import torch.nn as nn

In [2]:
# 创建一个全连接层（线性层）
linear = nn.Linear(5, 3)
print(linear.weight)

Parameter containing:
tensor([[-0.0962,  0.0112, -0.1837,  0.1918, -0.1889],
        [-0.0571,  0.3450, -0.4420, -0.2443,  0.3205],
        [ 0.4078, -0.2779,  0.2018,  0.2570, -0.2604]], requires_grad=True)


In [3]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [4]:
nn.init.ones_(linear.weight)
print(linear.weight)
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([10., 10., 10.], requires_grad=True)


In [5]:
# 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], requires_grad=True)


In [8]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, 1, 10)
print(linear.weight)

Parameter containing:
tensor([[9.1939, 6.0229, 5.2004, 1.4929, 2.0185],
        [2.3540, 5.0230, 7.6824, 2.5274, 9.6788],
        [7.9757, 9.0093, 3.7019, 7.7281, 2.6618]], requires_grad=True)


In [11]:
# 正态分布初始化
nn.init.normal_(linear.weight, 0, 1)
print(linear.weight)

Parameter containing:
tensor([[ 0.0277, -0.1478, -2.4340, -1.6469,  0.7556],
        [-0.5963,  0.2576, -0.5328,  0.6966, -0.2487],
        [-1.0870,  0.7915, -0.6709,  0.6640, -0.0920]], requires_grad=True)


In [12]:
# Xavier初始化
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.5165, -0.3391,  0.7468,  0.5884, -0.4691],
        [ 0.0384,  0.4186, -0.6496, -0.6328, -0.2501],
        [-0.0616, -0.3033,  0.3807, -0.1749,  0.0430]], requires_grad=True)


In [13]:
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-4.3231e-01,  4.4690e-01, -2.5546e-01,  1.1103e-01, -8.6266e-01],
        [ 7.3346e-01, -2.4518e-02,  1.0228e+00,  1.0613e+00,  9.0275e-03],
        [ 1.4739e+00, -5.4963e-01, -5.0915e-01,  4.4845e-01, -7.8554e-04]],
       requires_grad=True)


In [15]:
# He初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.4022,  0.3499, -0.3672, -0.4195,  0.2900],
        [-1.0192,  0.8545,  0.1494, -0.8236,  0.8895],
        [-0.1557, -0.9949, -0.6480, -0.6100,  0.4519]], requires_grad=True)


In [18]:
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.6510,  0.6335, -0.6008,  1.2024,  0.2882],
        [ 0.5802,  0.0327, -0.2266,  0.6493,  0.4725],
        [-0.5901,  0.3087, -0.8375,  0.2606,  0.2699]], requires_grad=True)
