In [5]:
import torch

In [6]:
# 随机生成一组x
x = torch.randint(low=1, high=10, size=(10,), dtype=torch.float)
print(x)

tensor([9., 9., 5., 7., 1., 3., 7., 4., 9., 2.])


In [7]:
# 定义一个Dropout层
dropout = torch.nn.Dropout(p=0.2)

In [8]:
print(dropout(x))

tensor([11.2500, 11.2500,  6.2500,  8.7500,  1.2500,  3.7500,  8.7500,  0.0000,
        11.2500,  0.0000])


In [10]:
x = torch.randn(10, 3, device=torch.device('cuda'))
print(x.device)

cuda:0


In [14]:
x2 = torch.randn(10, 3).to('cuda')
print(x2.device)

cuda:0


In [15]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print()

tensor([[[6, 8, 8, 5],
         [3, 5, 7, 3],
         [7, 6, 3, 3],
         [5, 1, 1, 4],
         [5, 6, 8, 5]],

        [[3, 5, 7, 3],
         [3, 6, 1, 8],
         [3, 4, 5, 6],
         [7, 3, 6, 4],
         [2, 6, 2, 5]],

        [[5, 6, 6, 4],
         [3, 2, 2, 1],
         [1, 5, 5, 8],
         [8, 4, 1, 4],
         [5, 3, 5, 4]]])



In [20]:
print(tensor1[[[0], [1]], 1:3, [1, 2]])

tensor([[[5, 6],
         [7, 3]],

        [[6, 4],
         [1, 5]]])
