In [1]:
import torch
import torch.nn as nn

## 全连接层

In [2]:
linear = nn.Linear(in_features=2, out_features=3, bias=True)

In [3]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3946, -0.0374],
        [ 0.1275, -0.6645],
        [-0.1802, -0.6524]], requires_grad=True)
Parameter containing:
tensor([ 0.0310,  0.1828, -0.5781], requires_grad=True)


## 向前传播

In [6]:
# 单条数据
#x = torch.tensor([1, 2]).float()

x = torch.randn(10, 2)

y = linear.forward(x)

print(y)

tensor([[-0.1473, -0.6573, -1.5026],
        [ 0.6757, -0.9764, -1.1765],
        [ 0.0409,  0.5598, -0.2166],
        [-0.2889,  1.2617,  0.1918],
        [ 0.1881,  0.6895,  0.0171],
        [-0.4413,  0.5928, -0.5523],
        [-0.3398,  0.8024, -0.2783],
        [ 0.1062,  0.9303,  0.1809],
        [-0.4232, -0.4222, -1.4916],
        [ 0.6136,  0.5718,  0.2300]], grad_fn=<AddmmBackward0>)


In [7]:
y = linear(x)  ## 相当于调用: linear.__call__(). 每个module都会在__call__内调用 self.forward
print(y)

tensor([[-0.1473, -0.6573, -1.5026],
        [ 0.6757, -0.9764, -1.1765],
        [ 0.0409,  0.5598, -0.2166],
        [-0.2889,  1.2617,  0.1918],
        [ 0.1881,  0.6895,  0.0171],
        [-0.4413,  0.5928, -0.5523],
        [-0.3398,  0.8024, -0.2783],
        [ 0.1062,  0.9303,  0.1809],
        [-0.4232, -0.4222, -1.4916],
        [ 0.6136,  0.5718,  0.2300]], grad_fn=<AddmmBackward0>)
