In [13]:
import torch
import torch.nn as nn

In [14]:
# 输入
x = torch.randn(3, 2)
print(x)

tensor([[-0.3958,  0.6753],
        [ 0.5925, -1.0583],
        [ 0.3941, -0.3670]])


In [24]:
# 真实值（标签）
t = torch.tensor([[0, 1], [1, 0], [0.2, 0.8]], dtype=torch.float)
# t = torch.tensor([1, 0, 0], dtype=torch.float)
print(t)

tensor([[0.0000, 1.0000],
        [1.0000, 0.0000],
        [0.2000, 0.8000]])


In [25]:
# 预测值（输出）
y = torch.sigmoid(x)
print(y)

tensor([[0.4023, 0.6627],
        [0.6439, 0.2576],
        [0.5973, 0.4093]])


In [26]:
# 定义损失函数，计算损失值
loss = nn.BCELoss()
print(loss(y, t))

tensor(0.5525)
