In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 真实值为类别标签(0 ~ 7)
x = torch.randn(6, 8)
print(x)

tensor([[-0.1055, -0.6212,  0.2267,  1.1066, -1.2997, -1.2886,  0.9181, -1.7108],
        [-0.2687, -1.6676,  0.9135, -1.2925, -0.9126, -0.0181,  0.5698,  1.1392],
        [-0.4626,  0.7050, -0.5032, -0.6495, -1.5294, -1.1014, -0.0325, -1.2344],
        [ 0.3870,  0.5134,  1.1989,  0.6660,  0.2450, -1.4631,  1.2697, -0.9406],
        [-1.3100, -0.6047, -1.2802,  0.9758, -0.0952,  0.8718,  1.1733,  0.0107],
        [-2.5446,  1.6546,  1.4438, -0.5305,  0.6743, -0.9450, -1.9234,  0.2364]])


In [3]:
t = torch.tensor([1, 0, 3, 2, 5, 7])
print(t)

tensor([1, 0, 3, 2, 5, 7])


In [4]:
# 计算损失
loss = nn.CrossEntropyLoss()
print(loss(x, t))

tensor(2.1887)


In [5]:
# 2. 真实值为分类概率或独热编码
t = torch.randn(6, 8).softmax(dim=1)
print(t)

tensor([[0.0688, 0.0277, 0.2592, 0.0791, 0.1954, 0.0385, 0.2511, 0.0802],
        [0.0279, 0.1591, 0.0353, 0.2533, 0.0659, 0.3910, 0.0451, 0.0224],
        [0.0698, 0.0391, 0.0089, 0.0156, 0.0410, 0.0261, 0.1929, 0.6066],
        [0.1213, 0.1123, 0.1167, 0.1054, 0.0477, 0.1407, 0.1357, 0.2203],
        [0.0416, 0.1274, 0.5185, 0.0987, 0.0128, 0.1251, 0.0113, 0.0647],
        [0.2871, 0.1186, 0.2262, 0.0051, 0.0829, 0.0303, 0.0883, 0.1614]])


In [6]:
loss = nn.CrossEntropyLoss()
print(loss(x, t))

tensor(2.7074)


In [7]:
input = torch.randn(6, 8)
print(input)
target = torch.randint(low=0, high=8, size=(6, ))
print(target)

tensor([[-2.3335, -0.4997, -0.1639,  0.6648, -0.4160,  0.3110, -1.6000, -0.2161],
        [ 0.0057,  0.1100,  0.3334,  0.5560,  0.6272, -1.8309, -0.0518, -0.8002],
        [-0.5280, -1.2105, -0.8286, -0.7652, -0.8130,  1.3968,  1.7120,  1.0564],
        [-0.1979, -0.7846,  1.4984, -0.7643, -0.4526, -0.4906, -2.5190,  0.9191],
        [-0.0755, -0.2226, -0.8889,  0.8268,  0.2199,  0.2336, -1.2075, -0.2504],
        [-0.4446,  0.3724,  0.0456,  1.3826, -0.5889, -0.3283, -1.3237,  0.7037]])
tensor([5, 1, 3, 3, 6, 7])


In [8]:
# 1. 直接调用 CrossEntropyLoss
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.5160)


In [10]:
# 2. 先调LogSoftmax，再调NLLLoss
loss1 = nn.LogSoftmax(dim=1)
loss2 = nn.NLLLoss()
y = loss1(input)
print(loss2(y, target))

tensor(2.5160)
