In [5]:
import torch
import numpy as np

In [6]:
# 1. 基本张量创建
# 1.1 torch.tensor(data)创建指定内容的张量，传入标量
tensor1 = torch.tensor(5)
print(tensor1)

tensor(5)


In [7]:
# 1.2 传入列表
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6]])  
print(tensor2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [25]:
# 1.3 传入ndarray
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print(tensor3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
# 2. torch.Tensor(size)创建指定形状的张量
tensor1 = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1.dtype)

torch.float32


In [20]:
tensor2 = torch.Tensor(4, 2, 3)
print(tensor2)

tensor([[[2.9454e-03, 1.3382e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [53]:
tensor3 = torch.Tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print(tensor3.dtype)
print(tensor3)

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)


In [27]:
# 3. 创建指定类型的张量
tensor1 = torch.IntTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32) torch.int32


In [107]:
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor2, tensor2.dtype)

tensor([1, 2, 3], dtype=torch.int32) torch.int32


In [33]:
tensor1 = torch.LongTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.int64


In [34]:
tensor1 = torch.ShortTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int16) torch.int16


In [42]:
tensor1 = torch.ByteTensor([[1.2, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.uint8) torch.uint8


In [38]:
tensor1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.float32


In [108]:
tensor1 = torch.DoubleTensor(3,2,4)
print(tensor1, tensor1.dtype)

tensor([[[2.0270e-311,  0.0000e+00,  0.0000e+00, 5.2635e-315],
         [ 0.0000e+00,  0.0000e+00, 5.2635e-315,  0.0000e+00]],

        [[ 0.0000e+00, 5.2635e-315,  0.0000e+00,  0.0000e+00],
         [5.2635e-315,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],
       dtype=torch.float64) torch.float64


In [41]:
tensor1 = torch.BoolTensor([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1, tensor1.dtype)

tensor([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]) torch.bool


In [54]:
# 4. 指定区间的张量创建
# 4.1 torch.arange(start, end, step)在区间内按步长创建张量
tensor1 = torch.arange(10, 30, 2)
print(tensor1, tensor1.dtype)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) torch.int64


In [55]:
tensor2 = torch.arange(9)
print(tensor2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [60]:
# 4.2 torch.linspace(start, end, steps)在区间内按元素数量创建张量
tensor1 = torch.linspace(10, 30, 7)
print(tensor1, tensor1.dtype)

tensor([10.0000, 13.3333, 16.6667, 20.0000, 23.3333, 26.6667, 30.0000]) torch.float32


In [62]:
# 4.3 torch.logspace(start, end, steps, base)在指数区间内按指定底数创建张量
tensor1 = torch.logspace(1, 3, 5, base=2)
print(tensor1)

tensor([2.0000, 2.8284, 4.0000, 5.6569, 8.0000])


In [64]:
# 5. 按数值填充张量
tensor1 = torch.zeros(2, 3)
print(tensor1, tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32


In [65]:
tensor2 = torch.ones(3, 2, 4)
print(tensor2, tensor2.dtype)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) torch.float32


In [66]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [69]:
tensor2 = torch.full((3, 2), 10.5)
print(tensor2, tensor2.dtype)

tensor([[10.5000, 10.5000],
        [10.5000, 10.5000],
        [10.5000, 10.5000]]) torch.float32


In [81]:
tensor2 = torch.full_like(tensor1, 10.5)
print(tensor2)

tensor([[10.5000, 10.5000, 10.5000],
        [10.5000, 10.5000, 10.5000]])


In [72]:
tensor3 = torch.empty(3, 2, 2)
print(tensor3, tensor3.dtype)

tensor([[[1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]]]) torch.float32


In [78]:
tensor3 = torch.empty_like(tensor2)
print(tensor3)

tensor([[2.9457e-03, 1.3382e-42, 1.6667e+01],
        [2.0000e+01, 2.3333e+01, 2.6667e+01]])


In [82]:
tensor3 = torch.eye(5)
print(tensor3)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [83]:
tensor3 = torch.eye(3, 5)
print(tensor3)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


In [86]:
# 6. 随机张量创建
# 6.1 均匀分布，[0, 1)
tensor1 = torch.rand(3, 2)
print(tensor1)

tensor([[0.9846, 0.0973],
        [0.4712, 0.4936],
        [0.8441, 0.3937]])


In [88]:
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.5994, 0.2344],
        [0.9613, 0.2783],
        [0.1932, 0.8801]])


In [87]:
# 6.2 均匀分布，整数
tensor2 = torch.randint(0, 100, (2, 3))
print(tensor2)

tensor([[ 8, 32, 26],
        [53, 69, 12]])


In [94]:
tensor3 = torch.randint_like(tensor2, 1, 10)
print(tensor3)

tensor([[4., 1.],
        [5., 1.],
        [6., 5.]])


In [92]:
# 6.3 标准正态分布
tensor1 = torch.randn(3, 2)
print(tensor1)

tensor([[ 0.0672, -0.4895],
        [-0.3012,  0.4954],
        [-0.2715,  0.5548]])


In [93]:
tensor2 = torch.randn_like(tensor3)
print(tensor2)

tensor([[ 0.9207,  0.5239],
        [-1.2136,  1.3014],
        [ 0.7276, -0.7019]])


In [95]:
# 6.4 自定义正态分布
tensor3 = torch.normal(5, 2, (4, 3))

In [96]:
print(tensor3)

tensor([[4.3614, 5.7379, 5.7325],
        [8.1146, 9.9953, 5.1754],
        [5.0028, 5.2079, 7.1531],
        [5.9795, 4.3575, 2.7905]])


In [99]:
# 6.5 生成随机排列的序列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([3, 4, 2, 9, 7, 6, 5, 1, 0, 8])


In [103]:
# 6.6 随机数种子
print(torch.random.initial_seed())

42


In [101]:
torch.manual_seed(42)