In [1]:
import numpy as np
import torch

In [4]:
# 1. 张量元素类型转换
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)
tensor1 = tensor1.type(torch.float64)
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [5]:
tensor1 = tensor1.int()
print(tensor1, tensor1.dtype)

tensor([1, 2, 3], dtype=torch.int32) torch.int32


In [6]:
tensor1 = tensor1.long()
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64


In [9]:
tensor1 = tensor1.bool()
print(tensor1, tensor1.dtype)

tensor([True, True, True]) torch.bool


In [11]:
tensor1 = tensor1.double()
print(tensor1, tensor1.dtype)

tensor([1., 1., 1.], dtype=torch.float64) torch.float64


In [17]:
np.set_printoptions(precision=8)
torch.set_printoptions(precision=8)
# 2. Tensor和ndarray的转换
# 2.1 将 Tensor 转为 ndarray
# 共享内存
tensor1 = torch.rand(3, 2)
np_array1 = tensor1.numpy()
print(tensor1, tensor1.dtype)
print(np_array1, np_array1.dtype)
print(type(tensor1), type(np_array1))

tensor([[0.85284102, 0.97877657],
        [0.21784359, 0.01214308],
        [0.85389620, 0.22518581]]) torch.float32
[[0.852841   0.9787766 ]
 [0.21784359 0.01214308]
 [0.8538962  0.22518581]] float32
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [18]:
tensor1[:, 0] = 10
print(tensor1)
print(np_array1)

tensor([[10.00000000,  0.97877657],
        [10.00000000,  0.01214308],
        [10.00000000,  0.22518581]])
[[10.          0.9787766 ]
 [10.          0.01214308]
 [10.          0.22518581]]


In [19]:
print(id(tensor1), id(np_array1))

2038890237616 2038887666512


In [20]:
# 使用copy方法，避免共享内存
np_array2 = tensor1.numpy().copy()
tensor1[:, 0] = 100
print(tensor1)
print(np_array1)
print(np_array2)

tensor([[1.00000000e+02, 9.78776574e-01],
        [1.00000000e+02, 1.21430755e-02],
        [1.00000000e+02, 2.25185812e-01]])
[[1.00000000e+02 9.78776574e-01]
 [1.00000000e+02 1.21430755e-02]
 [1.00000000e+02 2.25185812e-01]]
[[10.          0.9787766 ]
 [10.          0.01214308]
 [10.          0.22518581]]


In [21]:
# 2.2 将ndarray转换为 Tensor
# 共享内存
np_array = np.random.randn(3, 2)
tensor1 = torch.from_numpy(np_array)
print(tensor1, tensor1.dtype)
print(np_array)

tensor([[ 0.37925698, -0.38212115],
        [ 0.62677610, -0.93936099],
        [ 1.18456580, -0.49644658]], dtype=torch.float64) torch.float64
[[ 0.37925698 -0.38212115]
 [ 0.6267761  -0.93936099]
 [ 1.1845658  -0.49644658]]


In [22]:
np_array[0, 1] = 5
print(np_array)
print(tensor1)

[[ 0.37925698  5.        ]
 [ 0.6267761  -0.93936099]
 [ 1.1845658  -0.49644658]]
tensor([[ 0.37925698,  5.00000000],
        [ 0.62677610, -0.93936099],
        [ 1.18456580, -0.49644658]], dtype=torch.float64)


In [23]:
# 使用copy方法，避免共享内存
tensor2 = torch.from_numpy(np_array.copy())
np_array[0, 1] = 8
print(np_array)
print(tensor1)
print(tensor2)

[[ 0.37925698  8.        ]
 [ 0.6267761  -0.93936099]
 [ 1.1845658  -0.49644658]]
tensor([[ 0.37925698,  8.00000000],
        [ 0.62677610, -0.93936099],
        [ 1.18456580, -0.49644658]], dtype=torch.float64)
tensor([[ 0.37925698,  5.00000000],
        [ 0.62677610, -0.93936099],
        [ 1.18456580, -0.49644658]], dtype=torch.float64)


In [25]:
# 2.3 使用 tensor 方法，将ndarray转换成 Tensor；不共享内存
np_array = np.random.randn(3, 2)
tensor1 = torch.tensor(np_array)
print(np_array)
print(tensor1)

[[-0.48490053  3.48703111]
 [ 0.98515528  1.81246495]
 [ 0.09702788  1.78150421]]
tensor([[-0.48490053,  3.48703111],
        [ 0.98515528,  1.81246495],
        [ 0.09702788,  1.78150421]], dtype=torch.float64)


In [26]:
np_array[0, 1] = 5
print(np_array)
print(tensor1)

[[-0.48490053  5.        ]
 [ 0.98515528  1.81246495]
 [ 0.09702788  1.78150421]]
tensor([[-0.48490053,  3.48703111],
        [ 0.98515528,  1.81246495],
        [ 0.09702788,  1.78150421]], dtype=torch.float64)


In [31]:
# 3. 将单一元素的张量转换成标量
tensor1 = torch.tensor([[[2]]])
print(tensor1)
print(tensor1.item())

tensor([[[2]]])
2
