In [1]:
import numpy as np
import torch

In [2]:
# 1. 基本运算
# 1.1 四则运算
tensor1 = torch.randint(low=1, high=10, size=(2,3))
print(tensor1)
print(tensor1 + 10)
print(tensor1)

tensor([[9, 1, 8],
        [2, 5, 5]])
tensor([[19, 11, 18],
        [12, 15, 15]])
tensor([[9, 1, 8],
        [2, 5, 5]])


In [3]:
# 调用方法，非原地操作
print(tensor1.add(10))
print(tensor1)

tensor([[19, 11, 18],
        [12, 15, 15]])
tensor([[9, 1, 8],
        [2, 5, 5]])


In [4]:
# 调用方法，原地操作
print(tensor1.add_(10))
print(tensor1)

tensor([[19, 11, 18],
        [12, 15, 15]])
tensor([[19, 11, 18],
        [12, 15, 15]])


In [6]:
# 1.2 -、neg()、neg_()取负
print(-tensor1)
print(tensor1)

tensor([[-19, -11, -18],
        [-12, -15, -15]])
tensor([[19, 11, 18],
        [12, 15, 15]])


In [7]:
print(tensor1.neg())
print(tensor1)

tensor([[-19, -11, -18],
        [-12, -15, -15]])
tensor([[19, 11, 18],
        [12, 15, 15]])


In [8]:
print(tensor1.neg_())
print(tensor1)

tensor([[-19, -11, -18],
        [-12, -15, -15]])
tensor([[-19, -11, -18],
        [-12, -15, -15]])


In [9]:
# 1.3 **、pow()、pow_()求幂
tensor1 = torch.tensor([1, 2, 3])
print(tensor1**2)
print(tensor1)

tensor([1, 4, 9])
tensor([1, 2, 3])


In [10]:
print(tensor1.pow(2))
print(tensor1)

tensor([1, 4, 9])
tensor([1, 2, 3])


In [11]:
print(tensor1.pow_(2))
print(tensor1)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [12]:
# 1.4 sqrt()、sqrt_()求平方根
print(tensor1.sqrt())
print(tensor1)

tensor([1., 2., 3.])
tensor([1, 4, 9])


In [16]:
# tensor2 = tensor1.type(torch.float)
tensor2 = torch.Tensor([1, 2, 3])
print(tensor2)
print(tensor2.sqrt_())
print(tensor2)

tensor([1., 2., 3.])
tensor([1.0000, 1.4142, 1.7321])
tensor([1.0000, 1.4142, 1.7321])


In [20]:
# 1.5 exp()、exp_()以e为底数求幂
tensor1 = torch.tensor([1.0, 2, 3])
print(2.718281828459**tensor1)
print(tensor1.exp())
print(tensor1)

tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([1., 2., 3.])


In [21]:
print(tensor1.exp_())
print(tensor1)

tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [22]:
# 1.6 log()、log_()以e为底求对数
tensor1 = torch.tensor([1.0, 2, 3])
print(tensor1.log())
print(tensor1)

tensor([0.0000, 0.6931, 1.0986])
tensor([1., 2., 3.])


In [23]:
print(tensor1.log_())
print(tensor1)

tensor([0.0000, 0.6931, 1.0986])
tensor([0.0000, 0.6931, 1.0986])


In [28]:
# 2. 矩阵相关运算
# 2.1 哈达玛积
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor1 + tensor2)
print(tensor1 * tensor2)
print(tensor1 ** 2)
print(tensor1.mul(tensor2))

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [31]:
# 2.2 矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2],[3, 4], [5, 6]])
print(tensor1)
print(tensor2)
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
print(tensor1.mm(tensor2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


In [71]:
# 张量的矩阵乘法
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]],  [[6, 5, 4], [3, 2, 1]]])  # 2×2×3
tensor2 = torch.tensor([ [[1, 2, 3, 4],[3, 4, 2, 1], [5, 6, 7, 8]],  [[6, 5, 4, 3], [3, 2, 2, 1], [1, 0, 5, 3]] ])  # 2×3×4
# tensor2 = torch.tensor([ [[1, 2],[3, 4], [5, 6]] ])  # 1×3×2
print(tensor1)
print(tensor2)
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
# print(tensor1.mm(tensor2))    # 错误

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[6, 5, 4],
         [3, 2, 1]]])
tensor([[[1, 2, 3, 4],
         [3, 4, 2, 1],
         [5, 6, 7, 8]],

        [[6, 5, 4, 3],
         [3, 2, 2, 1],
         [1, 0, 5, 3]]])
tensor([[[22, 28, 28, 30],
         [49, 64, 64, 69]],

        [[55, 40, 54, 35],
         [25, 19, 21, 14]]])
tensor([[[22, 28, 28, 30],
         [49, 64, 64, 69]],

        [[55, 40, 54, 35],
         [25, 19, 21, 14]]])


In [70]:
# 内积：dot方法必须是一维向量相乘
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print(tensor1.dot(tensor2))


tensor(32)


In [74]:
# 节省内存
X = torch.randint(low=1, high=10, size=(3,2,4))
Y = torch.randint(low=1, high=10, size=(3,2,4))
print(id(X))
X *= Y
print(id(X))

2044048102880
2044048102880


In [80]:
X = torch.randint(low=1, high=10, size=(3,2,4))
Y = torch.randint(low=1, high=10, size=(3,4,4))
print(id(X))
print(X.shape)
# X = X @ Y
X @= Y
print(id(X))
print(X.shape)

2044048005056
torch.Size([3, 2, 4])
2044048004096
torch.Size([3, 2, 4])


In [92]:
X = torch.randint(low=1, high=10, size=(3,2,4))
Y = torch.randint(low=1, high=10, size=(3,4,1))
# X = np.array([[1, 2, 3], [4, 5, 6]])
# Y = np.array([[1,2,3], [3, 4,5], [5, 6,7]])
print(id(X))
print(X.shape)
print(X)
print(Y)
# X[:] = X @ Y
X @= Y
print(id(X))
print(X)

2044057436048
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [3 4 5]
 [5 6 7]]
2044057436048
[[22 28 34]
 [49 64 79]]
