In [9]:
import torch

In [19]:
tensor1 = torch.randint(low=0, high=10, size=(3,2,4)).float()
print(tensor1)

tensor([[[6., 2., 5., 4.],
         [0., 8., 6., 7.]],

        [[7., 7., 9., 7.],
         [4., 3., 3., 0.]],

        [[3., 4., 0., 4.],
         [9., 0., 2., 2.]]])


In [20]:
# sum求和
print("求和：", tensor1.sum())

求和： tensor(102.)


In [21]:
print("求和：", tensor1.sum(dim=2))

求和： tensor([[17., 21.],
        [30., 10.],
        [11., 13.]])


In [25]:
# mean求均值
print("求均值:", tensor1.mean(dim=0))

求均值: tensor([[5.3333, 4.3333, 4.6667, 5.0000],
        [4.3333, 3.6667, 3.6667, 3.0000]])


In [26]:
# std求标准差
print("求标准差：", tensor1.std(dim=1))

求标准差： tensor([[4.2426, 4.2426, 0.7071, 2.1213],
        [2.1213, 2.8284, 4.2426, 4.9497],
        [4.2426, 2.8284, 1.4142, 1.4142]])


In [28]:
# max/min
print("最大值：", tensor1.max())

最大值： tensor(9.)


In [32]:
# argmax/argmin
print("最小值索引：", tensor1.argmin())

最小值索引： tensor(4)


In [33]:
# unique去重
print(tensor1.unique())

tensor([0., 2., 3., 4., 5., 6., 7., 8., 9.])


In [46]:
tensor2 = torch.tensor([[[0., 8., 0., 7.],
         [6., 2., 6., 4.]],

        [[4., 3., 4., 0.],
         [7., 7., 7., 7.]],

        [[9., 0., 9., 2.],
         [3., 4., 3., 4.]]])
print(tensor2.unique(dim=2))

tensor([[[0., 7., 8.],
         [6., 4., 2.]],

        [[4., 0., 3.],
         [7., 7., 7.]],

        [[9., 2., 0.],
         [3., 4., 4.]]])


In [50]:
# sort 排序
print(tensor1.sort(dim=0, descending=True))

torch.return_types.sort(
values=tensor([[[7., 7., 9., 7.],
         [9., 8., 6., 7.]],

        [[6., 4., 5., 4.],
         [4., 3., 3., 2.]],

        [[3., 2., 0., 4.],
         [0., 0., 2., 0.]]]),
indices=tensor([[[1, 1, 1, 1],
         [2, 0, 0, 0]],

        [[0, 2, 0, 0],
         [1, 1, 1, 2]],

        [[2, 0, 2, 2],
         [0, 2, 2, 1]]]))
