In [2]:
import torch

In [9]:
tensor1 = torch.randint(low=0, high=10, size=(3, 5, 4))
print(tensor1)

tensor([[[9, 4, 5, 1],
         [5, 7, 2, 1],
         [4, 2, 7, 8],
         [6, 8, 5, 7],
         [2, 5, 3, 4]],

        [[6, 3, 0, 8],
         [9, 9, 4, 7],
         [3, 5, 2, 1],
         [7, 0, 8, 5],
         [0, 7, 7, 9]],

        [[5, 4, 5, 9],
         [7, 9, 1, 1],
         [5, 3, 0, 9],
         [7, 8, 4, 2],
         [4, 4, 0, 4]]])


In [10]:
# 简单索引
print(tensor1[0, 1, 2])
print(tensor1[1])
print(tensor1[0, 1])

tensor(2)
tensor([[6, 3, 0, 8],
        [9, 9, 4, 7],
        [3, 5, 2, 1],
        [7, 0, 8, 5],
        [0, 7, 7, 9]])
tensor([5, 7, 2, 1])


In [11]:
# 取所有矩阵第二行
print(tensor1[:,1])

tensor([[5, 7, 2, 1],
        [9, 9, 4, 7],
        [7, 9, 1, 1]])


In [12]:
# 范围索引
print(tensor1[1:])

tensor([[[6, 3, 0, 8],
         [9, 9, 4, 7],
         [3, 5, 2, 1],
         [7, 0, 8, 5],
         [0, 7, 7, 9]],

        [[5, 4, 5, 9],
         [7, 9, 1, 1],
         [5, 3, 0, 9],
         [7, 8, 4, 2],
         [4, 4, 0, 4]]])


In [13]:
print(tensor1[-1, 1:4, 0:3])

tensor([[7, 9, 1],
        [5, 3, 0],
        [7, 8, 4]])


In [14]:
print(tensor1[-1, 1:4:2, 0:3:2])
# print(tensor1[-1, 4:1:-2, 0:3:2])   # 错误写法

tensor([[7, 1],
        [7, 4]])


In [18]:
# 列表索引
print(tensor1)

tensor([[[9, 4, 5, 1],
         [5, 7, 2, 1],
         [4, 2, 7, 8],
         [6, 8, 5, 7],
         [2, 5, 3, 4]],

        [[6, 3, 0, 8],
         [9, 9, 4, 7],
         [3, 5, 2, 1],
         [7, 0, 8, 5],
         [0, 7, 7, 9]],

        [[5, 4, 5, 9],
         [7, 9, 1, 1],
         [5, 3, 0, 9],
         [7, 8, 4, 2],
         [4, 4, 0, 4]]])


In [22]:
print(tensor1[[0, 2], [1, 2]])

tensor([[5, 7, 2, 1],
        [5, 3, 0, 9]])


In [24]:
print(tensor1[[[0], [2]], [1, 2]])

tensor([[[5, 7, 2, 1],
         [4, 2, 7, 8]],

        [[7, 9, 1, 1],
         [5, 3, 0, 9]]])


In [27]:
# 布尔索引
mask = tensor1 > 5
print(tensor1[mask])

tensor([9, 7, 7, 8, 6, 8, 7, 6, 8, 9, 9, 7, 7, 8, 7, 7, 9, 9, 7, 9, 9, 7, 8])


In [30]:
# 选取首元素大于5的所有行
mask = tensor1[:, :, 0] > 5
print(mask)
print(tensor1[mask])

tensor([[ True, False, False,  True, False],
        [ True,  True, False,  True, False],
        [False,  True, False,  True, False]])
tensor([[9, 4, 5, 1],
        [6, 8, 5, 7],
        [6, 3, 0, 8],
        [9, 9, 4, 7],
        [7, 0, 8, 5],
        [7, 9, 1, 1],
        [7, 8, 4, 2]])


In [36]:
# 选取第二个元素大于5的所有列
mask = tensor1[:, 1, :] > 5
print(mask)
# print(tensor1[mask])
tensor2 = tensor1.permute(0, 2, 1)
print(tensor2)
print(tensor2[mask].T)

tensor([[False,  True, False, False],
        [ True,  True, False,  True],
        [ True,  True, False, False]])
tensor([[[9, 5, 4, 6, 2],
         [4, 7, 2, 8, 5],
         [5, 2, 7, 5, 3],
         [1, 1, 8, 7, 4]],

        [[6, 9, 3, 7, 0],
         [3, 9, 5, 0, 7],
         [0, 4, 2, 8, 7],
         [8, 7, 1, 5, 9]],

        [[5, 7, 5, 7, 4],
         [4, 9, 3, 8, 4],
         [5, 1, 0, 4, 0],
         [9, 1, 9, 2, 4]]])
tensor([[4, 6, 3, 8, 5, 4],
        [7, 9, 9, 7, 7, 9],
        [2, 3, 5, 1, 5, 3],
        [8, 7, 0, 5, 7, 8],
        [5, 0, 7, 9, 4, 4]])


In [37]:
mask = tensor1[:, 1, 3] > 5
print(tensor1[mask])

tensor([[[6, 3, 0, 8],
         [9, 9, 4, 7],
         [3, 5, 2, 1],
         [7, 0, 8, 5],
         [0, 7, 7, 9]]])
