In [2]:
import torch

In [3]:
# 交换维度
tensor1 = torch.randint(low=0, high=10, size=(3, 2, 5))
print(tensor1)

tensor([[[0, 1, 2, 6, 9],
         [8, 7, 6, 9, 6]],

        [[1, 8, 5, 5, 7],
         [9, 3, 0, 0, 0]],

        [[1, 5, 6, 6, 1],
         [3, 5, 5, 5, 9]]])


In [4]:
print(tensor1.transpose(-1, -2))

tensor([[[0, 8],
         [1, 7],
         [2, 6],
         [6, 9],
         [9, 6]],

        [[1, 9],
         [8, 3],
         [5, 0],
         [5, 0],
         [7, 0]],

        [[1, 3],
         [5, 5],
         [6, 5],
         [6, 5],
         [1, 9]]])


In [6]:
print(tensor1.transpose(0, 2))

tensor([[[0, 1, 1],
         [8, 9, 3]],

        [[1, 8, 5],
         [7, 3, 5]],

        [[2, 5, 6],
         [6, 0, 5]],

        [[6, 5, 6],
         [9, 0, 5]],

        [[9, 7, 1],
         [6, 0, 9]]])


In [8]:
print(tensor1.permute(1, 2, 0))

tensor([[[0, 1, 1],
         [1, 8, 5],
         [2, 5, 6],
         [6, 5, 6],
         [9, 7, 1]],

        [[8, 9, 3],
         [7, 3, 5],
         [6, 0, 5],
         [9, 0, 5],
         [6, 0, 9]]])


In [13]:
# 调整形状
print(tensor1.reshape(5, 6))
print(tensor1.reshape(3, -1))

tensor([[0, 1, 2, 6, 9, 8],
        [7, 6, 9, 6, 1, 8],
        [5, 5, 7, 9, 3, 0],
        [0, 0, 1, 5, 6, 6],
        [1, 3, 5, 5, 5, 9]])
tensor([[0, 1, 2, 6, 9, 8, 7, 6, 9, 6],
        [1, 8, 5, 5, 7, 9, 3, 0, 0, 0],
        [1, 5, 6, 6, 1, 3, 5, 5, 5, 9]])


In [15]:
# view视图
print(tensor1.is_contiguous())

True


In [16]:
print(tensor1.view(-1, 10))

tensor([[0, 1, 2, 6, 9, 8, 7, 6, 9, 6],
        [1, 8, 5, 5, 7, 9, 3, 0, 0, 0],
        [1, 5, 6, 6, 1, 3, 5, 5, 5, 9]])


In [19]:
tensor1 = tensor1.T
print(tensor1)
print(tensor1.is_contiguous())

tensor([[[0, 1, 1],
         [8, 9, 3]],

        [[1, 8, 5],
         [7, 3, 5]],

        [[2, 5, 6],
         [6, 0, 5]],

        [[6, 5, 6],
         [9, 0, 5]],

        [[9, 7, 1],
         [6, 0, 9]]])
False


In [22]:
print(tensor1.contiguous().view(-1))

tensor([0, 1, 1, 8, 9, 3, 1, 8, 5, 7, 3, 5, 2, 5, 6, 6, 0, 5, 6, 5, 6, 9, 0, 5,
        9, 7, 1, 6, 0, 9])


In [30]:
# 增加维度
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.shape)
print(tensor1.unsqueeze(dim=0))

torch.Size([3])
tensor([[1, 2, 3]])


In [33]:
print(tensor1.unsqueeze(dim=1))

tensor([[1],
        [2],
        [3]])


In [45]:
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2.shape)
print(tensor2.unsqueeze(dim=2))

torch.Size([2, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])


In [46]:
# 删除大小为1的维度
# 先增加维度1
print(tensor2.unsqueeze_(dim=1))
print(tensor2)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


In [50]:
print(tensor2.shape)
# 再删除维度1
print(tensor2.squeeze_(dim=1))
print(tensor2.shape)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [51]:
# 张量拼接
tensor1 = torch.randint(low=0, high=10, size=(2, 2, 5))
tensor2 = torch.randint(low=0, high=10, size=(2, 1, 5))
print(tensor1)
print(tensor2)

tensor([[[3, 9, 8, 8, 4],
         [3, 7, 3, 4, 1]],

        [[9, 7, 9, 1, 9],
         [5, 2, 0, 9, 8]]])
tensor([[[7, 3, 5, 3, 1]],

        [[2, 4, 0, 1, 1]]])


In [54]:
print(torch.cat([tensor1, tensor2], dim=1))

tensor([[[3, 9, 8, 8, 4],
         [3, 7, 3, 4, 1],
         [7, 3, 5, 3, 1]],

        [[9, 7, 9, 1, 9],
         [5, 2, 0, 9, 8],
         [2, 4, 0, 1, 1]]])


In [60]:
tensor1 = torch.randint(low=0, high=10, size=(3, 1, 5))
tensor2 = torch.randint(low=0, high=10, size=(3, 1, 5))
print(tensor1)
print(tensor2)

tensor([[[7, 7, 1, 3, 9]],

        [[8, 7, 2, 7, 0]],

        [[8, 8, 6, 0, 3]]])
tensor([[[3, 0, 2, 6, 6]],

        [[5, 6, 5, 9, 0]],

        [[5, 1, 6, 6, 8]]])


In [61]:
# 张量堆叠
tensor3 = torch.stack([tensor1, tensor2])
print(tensor3)
print(tensor3.shape)

tensor([[[[7, 7, 1, 3, 9]],

         [[8, 7, 2, 7, 0]],

         [[8, 8, 6, 0, 3]]],


        [[[3, 0, 2, 6, 6]],

         [[5, 6, 5, 9, 0]],

         [[5, 1, 6, 6, 8]]]])
torch.Size([2, 3, 1, 5])


In [64]:
tensor3 = torch.stack([tensor1, tensor2], dim=3)
print(tensor3)
print(tensor3.shape)

tensor([[[[7, 3],
          [7, 0],
          [1, 2],
          [3, 6],
          [9, 6]]],


        [[[8, 5],
          [7, 6],
          [2, 5],
          [7, 9],
          [0, 0]]],


        [[[8, 5],
          [8, 1],
          [6, 6],
          [0, 6],
          [3, 8]]]])
torch.Size([3, 1, 5, 2])
