In [41]:
import torch

In [42]:
# 定义输入数据x和标签y
x = torch.tensor(10.0, requires_grad=True)
y = torch.tensor([[3.0]])
# 初始化参数w和b
w = torch.rand(1, 1, requires_grad=True)
b = torch.rand(1, 1, requires_grad=True)

In [43]:
print(w)

tensor([[0.2120]], requires_grad=True)


In [44]:
# 计算，前向传播
z = w * x + b
z.retain_grad()
print(z)
print(z.requires_grad)

tensor([[2.9367]], grad_fn=<AddBackward0>)
True


In [45]:
# 设置损失函数
loss = torch.nn.MSELoss()
# 计算损失
loss_value = loss(z, y)
print(loss_value)

tensor(0.0040, grad_fn=<MseLossBackward0>)


In [46]:
# 反向传播
loss_value.backward()

In [47]:
print("w的梯度:", w.grad)
print("b的梯度：", b.grad)

w的梯度: tensor([[-1.2661]])
b的梯度： tensor([[-0.1266]])


In [49]:
print(z.grad)
# 判断是否是叶子节点
print(x.is_leaf)  # True
print(w.is_leaf)  # True
print(b.is_leaf)  # True
print(z.is_leaf)  # False
print(y.is_leaf)  # True
print(loss_value.is_leaf)  # False

print(x.grad)

tensor([[-0.1266]])
True
True
True
False
True
False
tensor(-0.0268)
