In [1]:
import torch

In [3]:
x = torch.tensor([1.0, 2, 3], requires_grad=True)
y = x.detach()

print(x)
print(y)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])


In [4]:
print(id(x))
print(id(y))

1543213136656
1542511357264


In [6]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

3555142467584
3555142467584


In [7]:
z1 = x ** 2
print(z1)
z2 = y ** 2
print(z2)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([1., 4., 9.])


In [9]:
print(z1.requires_grad)
z1.sum().backward()

True


In [11]:
print(z2.requires_grad)
# z2.sum().backward()

False


In [13]:
y[1] = 5
print(x)
print(y)

tensor([1., 5., 3.], requires_grad=True)
tensor([1., 5., 3.])


In [26]:
import numpy as np
# 测试detach对梯度的影响
x = torch.tensor(np.array([[3., 1.], [2., 4.]]), requires_grad=True)
print(x)
y = x * x
print(y)

tensor([[3., 1.],
        [2., 4.]], dtype=torch.float64, requires_grad=True)
tensor([[ 9.,  1.],
        [ 4., 16.]], dtype=torch.float64, grad_fn=<MulBackward0>)


In [27]:
# 用detach将y分离一份
u = y.detach()
print(u)

tensor([[ 9.,  1.],
        [ 4., 16.]], dtype=torch.float64)


In [28]:
# 用u和x进行计算
z = u * x
print(z)

tensor([[27.,  1.],
        [ 8., 64.]], dtype=torch.float64, grad_fn=<MulBackward0>)


In [29]:
z.sum().backward()

In [30]:
print(x.grad)
print(u.grad)

tensor([[ 9.,  1.],
        [ 4., 16.]], dtype=torch.float64)
None


In [31]:
print(x.grad == u)

tensor([[True, True],
        [True, True]])
