In [1]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset

In [2]:
t = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


In [3]:
ds = MyDataset(t)

print(len(ds))
print(ds[0:3])


15
tensor([1, 2, 3])


In [5]:
x = torch.randn(10, 3)
y = torch.randn(10)

print(x)
print(y)

tensor([[-0.2304, -1.0369,  0.7946],
        [-0.3972,  0.6706,  1.1437],
        [-0.2694, -0.4104, -0.8655],
        [-0.2802, -1.3592,  0.2480],
        [-1.0741, -0.5940,  0.8624],
        [ 1.2694, -2.3294,  0.3770],
        [-0.1737, -0.8914, -0.5370],
        [-1.7331,  1.4883,  1.0931],
        [ 0.1150, -0.4370,  0.6566],
        [ 0.9101,  1.5603, -0.5706]])
tensor([-1.4459,  0.8346,  1.1552,  0.3006,  0.1514, -0.4266, -0.5682,  0.0674,
         0.7213, -0.2174])
