In [4]:
import torch
# Dataset: 定义「单条数据怎么取」；DataLoader: 在其上做分批/打乱/迭代
# TensorDataset: 把已有张量直接打包成 Dataset 的内置工具
from torch.utils.data import Dataset, DataLoader, TensorDataset

In [5]:
t = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
# 自定义数据集：继承 Dataset，实现三个方法即可
class MyDataset(Dataset):
    def __init__(self, data):       # 接收并保存数据
        self.data = data

    def __len__(self):              # 返回样本总数 → 决定 len(ds)
        return len(self.data)

    def __getitem__(self, idx):     # 按下标取样本 → 决定 ds[idx]
        return self.data[idx]

In [6]:
ds = MyDataset(t)

print(len(ds))    # 调用 __len__ → 15
print(ds[0:3])    # 调用 __getitem__ → tensor([1, 2, 3])

15
tensor([1, 2, 3])


In [7]:
# 内置 TensorDataset：直接用张量构造，无需手写类。注意取出的是元组
ds = TensorDataset(t)
print(len(ds))
print(ds[0:3])    # (tensor([1, 2, 3]),) —— 单元素元组

15
(tensor([1, 2, 3]),)


In [8]:
x = torch.randn(10, 3)   # 10 条样本，每条 3 个特征
y = torch.randn(10)      # 10 个标签

print(x)
print(y)

tensor([[ 0.1352,  0.5919, -1.0043],
        [ 0.0985, -1.8259, -1.0765],
        [-0.6091, -2.3189, -0.8488],
        [-1.6001, -0.0566,  1.4533],
        [ 1.7983, -0.2654, -0.5099],
        [ 0.1243,  1.1136,  0.0957],
        [-0.3588,  0.4855,  1.5718],
        [ 0.1679,  1.8650,  0.7682],
        [ 0.7785,  0.2899,  0.0341],
        [-0.5206,  0.0316,  2.1429]])
tensor([-0.3011, -0.4649, -2.1689, -0.2963, -2.1583, -0.6152, -0.5669,  1.3882,
         0.1405,  0.7020])


In [9]:
# 把特征 x 和标签 y 打包：按第一维对齐，ds[i] 返回 (x[i], y[i]) 元组
ds = TensorDataset(x, y)
print(len(ds))
print(ds[0:3])   # (前3条特征, 前3个标签)

10
(tensor([[ 0.1352,  0.5919, -1.0043],
        [ 0.0985, -1.8259, -1.0765],
        [-0.6091, -2.3189, -0.8488]]), tensor([-0.3011, -0.4649, -2.1689]))


In [10]:
# DataLoader：分批迭代 Dataset
# batch_size=3 每批3条; shuffle=True 每个epoch打乱; drop_last=True 丢弃最后不满的批
# 10条数据 → 只产出 3 个完整批次（9条），剩 1 条被丢弃
loader = DataLoader(ds, batch_size=3, shuffle=True, drop_last=True)

In [11]:
# 迭代 loader，每次拿到一个 batch 的 (特征, 标签)
# 训练循环里就在这里：前向 → 算 loss → 反向 → 更新参数
for input, target in loader:
    print(input)
    print(target)

tensor([[-0.3588,  0.4855,  1.5718],
        [ 0.7785,  0.2899,  0.0341],
        [ 0.1352,  0.5919, -1.0043]])
tensor([-0.5669,  0.1405, -0.3011])
tensor([[-0.6091, -2.3189, -0.8488],
        [ 0.0985, -1.8259, -1.0765],
        [ 1.7983, -0.2654, -0.5099]])
tensor([-2.1689, -0.4649, -2.1583])
tensor([[-1.6001, -0.0566,  1.4533],
        [ 0.1243,  1.1136,  0.0957],
        [ 0.1679,  1.8650,  0.7682]])
tensor([-0.2963, -0.6152,  1.3882])
