In [12]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset

## 自定义数据集

In [13]:
t = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [14]:
ds = MyDataset(t)

print(len(ds))
print(ds[0:3])

15
tensor([1, 2, 3])


## 内置数据集: TensorDataset

In [15]:
ds = TensorDataset(t)
print(len(ds))
print(ds[0:3])

15
(tensor([1, 2, 3]),)


In [16]:
x = torch.randn(10, 3)
y = torch.randn(10)

print(x)
print(y)


tensor([[-2.5583, -0.6619, -0.0935],
        [-2.4056,  0.7842, -0.7350],
        [-1.5532, -1.2656,  0.3418],
        [-1.7380,  0.5789,  1.6270],
        [ 0.6526, -1.0715,  0.8066],
        [ 0.2820, -0.4457,  0.0884],
        [ 0.0900,  0.7615, -0.2266],
        [-1.4729,  0.1985,  0.3524],
        [ 0.7242, -0.8753,  0.7554],
        [ 0.4879,  1.5765, -1.8172]])
tensor([-1.1143,  0.6210,  0.7768, -0.8029,  0.6658,  1.2742, -0.5907, -0.1062,
        -0.5004, -0.6827])


In [32]:
ds = TensorDataset(x, y)
print(len(ds))
print(ds[0:3])

10
(tensor([[-2.5583, -0.6619, -0.0935],
        [-2.4056,  0.7842, -0.7350],
        [-1.5532, -1.2656,  0.3418]]), tensor([-1.1143,  0.6210,  0.7768]))


## DataLoader

In [77]:
loader = DataLoader(ds, batch_size=3, shuffle=True, drop_last=False)

In [82]:
for input, target in loader:
    print(input)
    print(target)


tensor([[-2.4056,  0.7842, -0.7350],
        [ 0.6526, -1.0715,  0.8066],
        [-1.4729,  0.1985,  0.3524]])
tensor([ 0.6210,  0.6658, -0.1062])
tensor([[-2.5583, -0.6619, -0.0935],
        [ 0.0900,  0.7615, -0.2266],
        [-1.5532, -1.2656,  0.3418]])
tensor([-1.1143, -0.5907,  0.7768])
tensor([[-1.7380,  0.5789,  1.6270],
        [ 0.2820, -0.4457,  0.0884],
        [ 0.4879,  1.5765, -1.8172]])
tensor([-0.8029,  1.2742, -0.6827])
tensor([[ 0.7242, -0.8753,  0.7554]])
tensor([-0.5004])
