In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 准备数据
x = torch.tensor([10.0], requires_grad=True)
y = torch.tensor([20.0], requires_grad=True)

In [3]:
# 2. 定义参数
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
print(w, b)

tensor(1., requires_grad=True) tensor(1., requires_grad=True)


In [4]:
# 3. 向前传播
z = w * x + b
z.retain_grad()

In [5]:
# 4. 定义损失函数计算损失
loss_fn = nn.MSELoss()
loss = loss_fn(z, y)
loss.retain_grad()

In [6]:
# 5. 反向传播计算梯度: backward 必须是在标量上调用
loss.backward()

In [7]:
print(loss.grad)
print(z.grad)
print(w.grad)
print(b.grad)
print(x.grad)
print(y.grad)

tensor(1.)
tensor([-18.])
tensor(-180.)
tensor(-18.)
tensor([-18.])
tensor([18.])


In [8]:
z = w * x + b
z.retain_grad()
loss = loss_fn(z, y)
loss.backward()

print(loss.grad)
print(z.grad)
print(w.grad)
print(b.grad)
print(x.grad)
print(y.grad)

None
tensor([-18.])
tensor(-360.)
tensor(-36.)
tensor([-36.])
tensor([36.])


/var/folders/6h/9dkxkng179j960736y5l8y640000gn/T/ipykernel_26298/3373448513.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:497.)
  print(loss.grad)


In [9]:
print(x.is_leaf)
print(y.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(z.is_leaf)
print(loss.is_leaf)

True
True
True
True
False
False
